// Locally-known app -> category fallback, used when the OS doesn't expose a
// category (Windows has no equivalent to macOS's LSApplicationCategoryType
// for arbitrary installed programs) or when macOS metadata lookup misses.
const KNOWN_APP_CATEGORIES: Record<string, string> = {
  'visual studio code': 'Developer Tools',
  vscodium: 'Developer Tools',
  cursor: 'Developer Tools',
  code: 'Developer Tools',
  xcode: 'Developer Tools',
  'android studio': 'Developer Tools',
  'intellij idea': 'Developer Tools',
  pycharm: 'Developer Tools',
  webstorm: 'Developer Tools',
  clion: 'Developer Tools',
  datagrip: 'Developer Tools',
  rubymine: 'Developer Tools',
  'sublime text': 'Developer Tools',
  vim: 'Developer Tools',
  neovim: 'Developer Tools',
  terminal: 'Developer Tools',
  iterm2: 'Developer Tools',
  iterm: 'Developer Tools',
  warp: 'Developer Tools',
  hyper: 'Developer Tools',
  'windows terminal': 'Developer Tools',
  powershell: 'Developer Tools',
  cmd: 'Developer Tools',
  docker: 'Developer Tools',
  'docker desktop': 'Developer Tools',
  postman: 'Developer Tools',
  insomnia: 'Developer Tools',
  tableplus: 'Developer Tools',
  'sequel pro': 'Developer Tools',
  'sequel ace': 'Developer Tools',
  dbeaver: 'Developer Tools',
  'mongodb compass': 'Developer Tools',
  'github desktop': 'Developer Tools',
  gitkraken: 'Developer Tools',
  fork: 'Developer Tools',
  'sourcetree': 'Developer Tools',
  claude: 'Developer Tools',
  'google chrome': 'Web Browser',
  chrome: 'Web Browser',
  safari: 'Web Browser',
  firefox: 'Web Browser',
  'microsoft edge': 'Web Browser',
  msedge: 'Web Browser',
  'brave browser': 'Web Browser',
  arc: 'Web Browser',
  opera: 'Web Browser',
  slack: 'Communication',
  discord: 'Communication',
  'microsoft teams': 'Communication',
  teams: 'Communication',
  zoom: 'Communication',
  'zoom.us': 'Communication',
  messages: 'Communication',
  mail: 'Communication',
  outlook: 'Communication',
  telegram: 'Communication',
  whatsapp: 'Communication',
  skype: 'Communication',
  figma: 'Design',
  sketch: 'Design',
  'adobe photoshop': 'Design',
  photoshop: 'Design',
  'adobe illustrator': 'Design',
  illustrator: 'Design',
  'affinity designer': 'Design',
  'affinity photo': 'Design',
  notion: 'Productivity',
  obsidian: 'Productivity',
  evernote: 'Productivity',
  'microsoft word': 'Productivity',
  winword: 'Productivity',
  'microsoft excel': 'Productivity',
  excel: 'Productivity',
  'microsoft powerpoint': 'Productivity',
  powerpnt: 'Productivity',
  pages: 'Productivity',
  numbers: 'Productivity',
  keynote: 'Productivity',
  spotify: 'Entertainment',
  'apple music': 'Entertainment',
  music: 'Entertainment',
  netflix: 'Entertainment',
  steam: 'Entertainment',
  vlc: 'Entertainment',
  finder: 'Utilities',
  explorer: 'Utilities',
  'activity monitor': 'Utilities',
  'task manager': 'Utilities',
  'system preferences': 'Utilities',
  'system settings': 'Utilities'
}

export function lookupKnownCategory(appName: string | null | undefined): string | null {
  if (!appName) return null
  return KNOWN_APP_CATEGORIES[appName.trim().toLowerCase()] ?? null
}

export function isDevToolsApp(appName: string | null | undefined): boolean {
  return lookupKnownCategory(appName) === 'Developer Tools'
}
